//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace try1
{
    internal class Student
    {
        public string Name { get; set; }
        public int RollNumber { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int AdmissionNumber { get; set; }
    }
}